services:
  bdd:
    container_name: bdd
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=${MYSQL_ROOT_PASS} --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  symfony:
    container_name: symfony
    build:
      context: .
      dockerfile: ./docker/symfony/Dockerfile
    volumes:
      - ./app:/var/www/html
    environment:
      DATABASE_URL: mysql://${MYSQL_USER_NAME}:${MYSQL_USER_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?serverVersion=5.7
    links:
      - bdd
    depends_on:
      bdd:
        condition: service_healthy

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./app/public:/var/www/html/public
    ports: # <Port exposed>:<Port running inside container>
      - "8080:80"   # http://127.0.0.1:8080
    depends_on:
      - symfony
      - bdd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - bdd
    depends_on:
      bdd:
        condition: service_healthy
    ports:
      - "8083:80"
    environment:
      PMA_HOST: bdd
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

volumes:
  dbdata: